name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: jun23
      TAG: latest
      CONTAINER_NAME: mycontainerv3
      PORT: 3000

    steps:
      - name: üîÑ Checkout Code
        uses: actions/checkout@v4

      - name: ‚öôÔ∏è Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG .

      - name: üßπ Remove Old Container If Exists
        run: |
          if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
          fi

      - name: üöÄ Run Docker Container
        run: |
          docker run -d --name $CONTAINER_NAME -p $PORT:$PORT ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG

      - name: üì§ Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG






