name: ğŸš€ Docker Build, Run and Push

on:
  push:
    branches:
      - main

jobs:
  build-run-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸ› ï¸ Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jun23:latest .

      - name: ğŸš€ Run Docker Container (optional)
        run: docker run -d -p 3000:3000 --name jun23container ${{ secrets.DOCKER_USERNAME }}/jun23:latest

      - name: ğŸ“¤ Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jun23:latest

